"""
A component which allows you to update your custom cards and components.

For more details about this component, please refer to the documentation at
https://github.com/custom-components/custom_updater
"""

import logging
import os
import subprocess
import time
from datetime import timedelta

import homeassistant.helpers.config_validation as cv
import requests
import voluptuous as vol
from homeassistant.components.sensor import PLATFORM_SCHEMA
from homeassistant.helpers.event import track_time_interval

__version__ = '1.4.1'

_LOGGER = logging.getLogger(__name__)

CONF_TRACK = 'track'
CONF_HIDE_SENSOR = 'hide_sensor'

DOMAIN = 'custom_updater'
CARD_DATA = 'custom_card_data'
COMPONENT_DATA = 'custom_component_data'
INTERVAL = timedelta(days=1)

ATTR_CARD = 'card'
ATTR_COMPONENT = 'component'

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({
    vol.Required(CONF_TRACK, default=None):
        vol.All(cv.ensure_list, [cv.string]),
    vol.Optional(CONF_HIDE_SENSOR, default=False): cv.boolean,
})

CARDS_JSON = 'https://raw.githubusercontent.com/custom-cards/information/master/repos.json'
COMPS_JSON = 'https://raw.githubusercontent.com/custom-components/information/master/repos.json'


def setup(hass, config):
    """Set up this component."""
    conf_track = config.get(CONF_TRACK)
    conf_hide_sensor = config.get(CONF_HIDE_SENSOR)
    _LOGGER.info('version %s is starting, if you have ANY issues with this, please report'
                 ' them here: https://github.com/custom-components/custom_updater', __version__)

    ha_conf_dir = str(hass.config.path())
    if not conf_track or 'cards' in conf_track:
        card_controller = CustomCards(hass, ha_conf_dir, conf_hide_sensor)
        track_time_interval(hass, card_controller.cache_versions, INTERVAL)
    if not conf_track or 'components' in conf_track:
        components_controller = CustomComponents(hass, ha_conf_dir, conf_hide_sensor)
        track_time_interval(hass, components_controller.cache_versions, INTERVAL)

    def check_all_service(call):
        """Set up service for manual trigger."""
        if not conf_track or 'cards' in conf_track:
            card_controller.cache_versions()
        if not conf_track or 'components' in conf_track:
            components_controller.cache_versions()

    def update_all_service():
        """Set up service for manual trigger."""
        if not conf_track or 'cards' in conf_track:
            card_controller.update_all()
        if not conf_track or 'components' in conf_track:
            components_controller.update_all()

    if not conf_track or 'cards' in conf_track:
        def upgrade_card_service(call):
            """Set up service for manual trigger."""
            card_controller.upgrade_single(call.data.get(ATTR_CARD))
        hass.services.register(DOMAIN, 'upgrade_single_card', upgrade_card_service)

    if not conf_track or 'components' in conf_track:
        def upgrade_component_service(call):
            """Set up service for manual trigger."""
            components_controller.upgrade_single(call.data.get(ATTR_COMPONENT))
        hass.services.register(DOMAIN, 'upgrade_single_component', upgrade_component_service)

    hass.services.register(DOMAIN, 'check_all', check_all_service)
    hass.services.register(DOMAIN, 'update_all', update_all_service)
    return True


class CustomUpdaterController(object):
    """Custom updater controller."""
    def __init__(self, hass, ha_conf_dir, conf_hide_sensor):
        self.hass = hass
        self._hide_sensor = conf_hide_sensor
        self.ha_conf_dir = ha_conf_dir

    @staticmethod
    def get_all_available_entities(url):
        """Get all available entities"""
        _LOGGER.debug('Gathering all available entities.')
        entities = []
        response = requests.get(url)
        if response.status_code == 200:
            for card in response.json():
                entities.append(card)
        else:
            _LOGGER.debug('Could not reach the remote information repo.')
        return entities


class CustomCards(CustomUpdaterController):
    """Custom cards controller."""
    def __init__(self, hass, ha_conf_dir, conf_hide_sensor):
        super().__init__(hass, ha_conf_dir, conf_hide_sensor)
        self.cards = None
        self._lovelace_gen = False
        self.hass.data[CARD_DATA] = {}
        self.lovelace_gen_check()
        self.cache_versions()

    def lovelace_gen_check(self):
        """Check if lovelace-gen is in use"""
        conf_file = self.ha_conf_dir + '/ui-lovelace.yaml'
        with open(conf_file, 'r') as local:
            for line in local.readlines():
                if 'generated by lovelace-gen.py' in line:
                    self._lovelace_gen = True
        local.close()
        if self._lovelace_gen and os.path.isdir(self.ha_conf_dir + '/lovelace'):
            _LOGGER.debug('Found evidence of lovelace-gen useage, assuming that is beeing used.')
            self._lovelace_gen = True
        else:
            self._lovelace_gen = False

    def cache_versions(self):
        """Cache"""
        self.cards = super().get_all_available_entities(CARDS_JSON)
        self.hass.data[CARD_DATA] = {}
        if self.cards:
            for card in self.cards:
                remote_info = self.get_remote_info(card)
                remote_version = remote_info[1]
                local_version = self.get_local_version(remote_info[0])
                if local_version:
                    has_update = (remote_version != False and remote_version != local_version)
                    not_local = (remote_version != False and not local_version)
                    self.hass.data[CARD_DATA][card] = {
                        "local": local_version,
                        "remote": remote_version,
                        "has_update": has_update,
                        "not_local": not_local,
                        "repo": remote_info[3],
                        "change_log": remote_info[4],
                    }
                    self.hass.data[CARD_DATA]['domain'] = 'custom_cards'
                    self.hass.data[CARD_DATA]['repo'] = '#'
                    if self._hide_sensor:
                        self.hass.data[CARD_DATA]['hidden'] = True
            self.hass.states.set('sensor.custom_card_tracker', time.time(), self.hass.data[CARD_DATA])

    def update_all(self):
        """Update all cards"""
        for card in self.hass.data[CARD_DATA]:
            if card not in ('domain', 'repo', 'hidden'):
                try:
                    if self.hass.data[CARD_DATA][card]['has_update'] and not self.hass.data[CARD_DATA][card]['not_local']:
                        self.upgrade_single(card)
                except:
                    _LOGGER.debug('Skipping upgrade for %s, no update available', card)

    def upgrade_single(self, card):
        """Update one components"""
        _LOGGER.debug('Starting upgrade for "%s".', card)
        if card in self.hass.data[CARD_DATA]:
            if self.hass.data[CARD_DATA][card]['has_update']:
                remote_info = self.get_remote_info(card)
                remote_file = remote_info[2]
                local_file = self.ha_conf_dir + self.get_card_dir(card) + card + '.js'
                test_remote_file = requests.get(remote_file)
                if test_remote_file.status_code == 200:
                    with open(local_file, 'wb') as card_file:
                        card_file.write(test_remote_file.content)
                    card_file.close()
                    self.update_resource_version(card)
                    _LOGGER.info('Upgrade of %s from version %s to version %s complete',
                                 card, self.hass.data[CARD_DATA][card]['local'],
                                 self.hass.data[CARD_DATA][card]['remote'])
                self.hass.data[CARD_DATA][card]['local'] = self.hass.data[CARD_DATA][card]['remote']
                self.hass.data[CARD_DATA][card]['has_update'] = False
                self.hass.data[CARD_DATA][card]['not_local'] = False
                self.hass.states.set('sensor.custom_card_tracker', time.time(), self.hass.data[CARD_DATA])
            else:
                _LOGGER.debug('Skipping upgrade for %s, no update available', card)
        else:
            _LOGGER.error('Upgrade failed, "%s" is not a valid card', card)

    def update_resource_version(self, card):
        """Updating the ui-lovelace file"""
        local_version = self.hass.data[CARD_DATA][card]['local']
        remote_version = self.hass.data[CARD_DATA][card]['remote']
        _LOGGER.debug('Updating configuration for %s', card)
        _LOGGER.debug('Upgrading card in config from version %s to version %s', local_version, remote_version)
        if self._lovelace_gen:
            conf_file = self.ha_conf_dir + '/lovelace/main.yaml'
            sedcmd = 's/' + card + '.js?v=' + str(local_version) + '/' + card + '.js?v=' + str(remote_version) + '/'
        else:
            conf_file = self.ha_conf_dir + '/ui-lovelace.yaml'
            sedcmd = 's/\/' + card + '.js?v=' + str(local_version) + '/\/' + card + '.js?v=' + str(remote_version) + '/'
        subprocess.call(["sed", "-i", "-e", sedcmd, conf_file])

    def get_card_dir(self, card):
        """Get card dir"""
        if self._lovelace_gen:
            conf_file = self.ha_conf_dir + '/lovelace/main.yaml'
        else:
            conf_file = self.ha_conf_dir + '/ui-lovelace.yaml'
        with open(conf_file, 'r') as local:
            for line in local.readlines():
                if self._lovelace_gen:
                    if card + '.js' in line:
                        card_dir = '/lovelace/' + line.split('!resource ')[1].split(card + '.js')[0]
                        _LOGGER.debug('Found path "%s" for card "%s"', card_dir, card)
                        break
                else:
                    if '/' + card + '.js' in line:
                        card_dir = line.split(': ')[1].split(card + '.js')[0].replace("local", "www")
                        _LOGGER.debug('Found path "%s" for card "%s"', card_dir, card)
                        break
        return card_dir

    @staticmethod
    def get_remote_info(card):
        """Return the remote info if any."""
        response = requests.get(CARDS_JSON)
        remote_info = [None]
        if response.status_code == 200:
            try:
                remote = response.json()[card]
                remote_info = [
                    card,
                    remote['version'],
                    remote['remote_location'],
                    remote['visit_repo'],
                    remote['changelog']
                ]
            except:
                _LOGGER.debug('Gathering remote info for %s failed...', card)
                remote = False
        else:
            _LOGGER.debug('Could not get remote info for %s', card)
        return remote_info

    def get_local_version(self, card):
        """Return the local version if any."""
        card_config = ''
        if self._lovelace_gen:
            conf_file = self.ha_conf_dir + '/lovelace/main.yaml'
            with open(conf_file, 'r') as local:
                for line in local.readlines():
                    if card + '.js' in line:
                        card_config = line
                        break
            local.close()
        else:
            conf_file = self.ha_conf_dir + '/ui-lovelace.yaml'
            with open(conf_file, 'r') as local:
                for line in local.readlines():
                    if '/' + card + '.js' in line:
                        card_config = line
                        break
            local.close()
        if '=' in card_config:
            local_version = card_config.split('=')[1].split('\n')[0]
            _LOGGER.debug('Local version of %s is %s', card, local_version)
            return local_version
        return False


class CustomComponents(CustomUpdaterController):
    """Custom components controller."""
    def __init__(self, hass, ha_conf_dir, conf_hide_sensor):
        super().__init__(hass, ha_conf_dir, conf_hide_sensor)
        self.components = None
        self.hass.data[COMPONENT_DATA] = {}
        self.cache_versions()

    def cache_versions(self):
        """Cache"""
        self.components = super().get_all_available_entities(COMPS_JSON)
        self.hass.data[COMPONENT_DATA] = {}
        if self.components:
            for component in self.components:
                remote_info = self.get_remote_info(component)
                remote_version = remote_info[1]
                local_version = self.get_local_version(component, remote_info[2])
                if local_version:
                    has_update = (remote_version != False and remote_version != local_version)
                    not_local = (remote_version != False and not local_version)
                    self.hass.data[COMPONENT_DATA][component] = {
                        "local": local_version,
                        "remote": remote_version,
                        "has_update": has_update,
                        "not_local": not_local,
                        "repo": remote_info[4],
                        "change_log": remote_info[5],
                    }
                    self.hass.data[COMPONENT_DATA]['domain'] = 'custom_components'
                    self.hass.data[COMPONENT_DATA]['repo'] = '#'
                    if self._hide_sensor:
                        self.hass.data[COMPONENT_DATA]['hidden'] = True
            self.hass.states.set('sensor.custom_component_tracker', time.time(), self.hass.data[COMPONENT_DATA])

    def update_all(self):
        """Update all components"""
        for component in self.hass.data[COMPONENT_DATA]:
            if component not in ('domain', 'repo'):
                try:
                    if self.hass.data[COMPONENT_DATA][component]['has_update'] and not self.hass.data[COMPONENT_DATA][component]['not_local']:
                        self.upgrade_single(component)
                except:
                    _LOGGER.debug('Skipping upgrade for %s, no update available', component)

    def upgrade_single(self, component):
        """Update one components"""
        _LOGGER.debug('Starting upgrade for "%s".', component)
        if component in self.hass.data[COMPONENT_DATA]:
            if self.hass.data[COMPONENT_DATA][component]['has_update']:
                remote_info = self.get_remote_info(component)
                remote_file = remote_info[3]
                local_file = self.ha_conf_dir + remote_info[2]
                test_remote_file = requests.get(remote_file)
                if test_remote_file.status_code == 200:
                    with open(local_file, 'wb') as component_file:
                        component_file.write(test_remote_file.content)
                    component_file.close()
                    _LOGGER.info('Upgrade of %s from version %s to version %s complete',
                                 component, self.hass.data[COMPONENT_DATA][component]['local'],
                                 self.hass.data[COMPONENT_DATA][component]['remote'])
                self.hass.data[COMPONENT_DATA][component]['local'] = self.hass.data[COMPONENT_DATA][component]['remote']
                self.hass.data[COMPONENT_DATA][component]['has_update'] = False
                self.hass.data[COMPONENT_DATA][component]['not_local'] = False
                self.hass.states.set('sensor.custom_component_tracker', time.time(), self.hass.data[COMPONENT_DATA])
            else:
                _LOGGER.debug('Skipping upgrade for %s, no update available', component)
        else:
            _LOGGER.error('Upgrade failed, "%s" is not a valid component', component)

    @staticmethod
    def get_remote_info(component):
        """Return the remote info if any."""
        response = requests.get(COMPS_JSON)
        remote_info = [None]
        if response.status_code == 200:
            try:
                remote = response.json()[component]
                remote_info = [
                    component,
                    remote['version'],
                    remote['local_location'],
                    remote['remote_location'],
                    remote['visit_repo'],
                    remote['changelog']
                ]
            except:
                _LOGGER.debug('Gathering remote info for %s failed...', component)
                remote = False
        else:
            _LOGGER.debug('Could not get remote info for %s', component)
        return remote_info

    def get_local_version(self, component, local_path):
        """Return the local version if any."""
        local_version = None
        component_path = self.ha_conf_dir + local_path
        if os.path.isfile(component_path):
            with open(component_path, 'r') as local:
                for line in local.readlines():
                    if '__version__' in line:
                        local_version = line.split("'")[1]
                        break
            local.close()
            if not local_version:
                local_v = False
                _LOGGER.debug('Could not get the local version for %s', component)
            else:
                local_v = local_version
                _LOGGER.debug('Local version of %s is %s', component, local_version)
        else:
            local_v = False
        return local_v
